### ISSUE TITLE
[dvalin-jaxrs][1.22] Default port for REST is 8080 while swagger-ui wil call port 80.

### ISSUE THREAD

**Issue by Thadoy** [taimos/dvalin#60]
The default settings set the server URL for the REST interface to `localhost:8080/`. But swagger-ui will perform all calls against `localhost:80/`

Setting the `server.url` property fixes the problem, so just the default settings are affected.

To me it looks like in `de.taimos.dvalin.jaxrs.swagger.ApiListing` in `configrueServerURL `the default is set to localhost. 
```
private void configureServerURL(Swagger swagger) {
        URLUtils.SplitURL split = URLUtils.splitURL(System.getProperty(SpringCXFProperties.SERVER_URL, "localhost"));
```

**Comment by hoegertn** [comment]
Great catch, I will check it and try to fix it.
