### ISSUE TITLE
Replacement of dead mongo projects fongo and mongobee

### ISSUE THREAD

**Issue by YukiInu** [taimos/dvalin#86]
For one of the next releases the dead projects fongo and mongobee should be replaced.

Fongo is no longer compatible with mongo-java-driver 3.6 an higher and therefore not compatible with MongoDB higher than 3.6
An alternative could be: https://github.com/bwaldvogel/mongo-java-server

Mongobee is also no longer supported and has some incompatibility problems with MongoDB 4.2
Here an alternative could be https://github.com/cloudyrock/mongock/ that began as a mongobee fork and therefore migration should be straight forward.

**Comment by hoegertn** [comment]
Is this something you would be able and willing to do?

**Comment by YukiInu** [comment]
I think so. Will try to implement it.

**Comment by YukiInu** [comment]
Done with the following two pull requets:
https://github.com/taimos/dvalin/pull/98
https://github.com/taimos/dvalin/pull/125
